/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardRescheduleIndexRouteImport } from './routes/dashboard/reschedule/index'
import { Route as DashboardSubareasCreateRouteImport } from './routes/dashboard/subareas/create'
import { Route as DashboardEventsCreateRouteImport } from './routes/dashboard/events/create'
import { Route as DashboardAreasCreateRouteImport } from './routes/dashboard/areas/create'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRescheduleIndexRoute =
  DashboardRescheduleIndexRouteImport.update({
    id: '/dashboard/reschedule/',
    path: '/dashboard/reschedule/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSubareasCreateRoute = DashboardSubareasCreateRouteImport.update({
  id: '/dashboard/subareas/create',
  path: '/dashboard/subareas/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsCreateRoute = DashboardEventsCreateRouteImport.update({
  id: '/dashboard/events/create',
  path: '/dashboard/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAreasCreateRoute = DashboardAreasCreateRouteImport.update({
  id: '/dashboard/areas/create',
  path: '/dashboard/areas/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/status': typeof StatusRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/areas/create': typeof DashboardAreasCreateRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/subareas/create': typeof DashboardSubareasCreateRoute
  '/dashboard/reschedule/': typeof DashboardRescheduleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/status': typeof StatusRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/areas/create': typeof DashboardAreasCreateRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/subareas/create': typeof DashboardSubareasCreateRoute
  '/dashboard/reschedule': typeof DashboardRescheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/status': typeof StatusRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/areas/create': typeof DashboardAreasCreateRoute
  '/dashboard/events/create': typeof DashboardEventsCreateRoute
  '/dashboard/subareas/create': typeof DashboardSubareasCreateRoute
  '/dashboard/reschedule/': typeof DashboardRescheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/status'
    | '/dashboard/'
    | '/dashboard/areas/create'
    | '/dashboard/events/create'
    | '/dashboard/subareas/create'
    | '/dashboard/reschedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/status'
    | '/dashboard'
    | '/dashboard/areas/create'
    | '/dashboard/events/create'
    | '/dashboard/subareas/create'
    | '/dashboard/reschedule'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/status'
    | '/dashboard/'
    | '/dashboard/areas/create'
    | '/dashboard/events/create'
    | '/dashboard/subareas/create'
    | '/dashboard/reschedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StatusRoute: typeof StatusRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAreasCreateRoute: typeof DashboardAreasCreateRoute
  DashboardEventsCreateRoute: typeof DashboardEventsCreateRoute
  DashboardSubareasCreateRoute: typeof DashboardSubareasCreateRoute
  DashboardRescheduleIndexRoute: typeof DashboardRescheduleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reschedule/': {
      id: '/dashboard/reschedule/'
      path: '/dashboard/reschedule'
      fullPath: '/dashboard/reschedule/'
      preLoaderRoute: typeof DashboardRescheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subareas/create': {
      id: '/dashboard/subareas/create'
      path: '/dashboard/subareas/create'
      fullPath: '/dashboard/subareas/create'
      preLoaderRoute: typeof DashboardSubareasCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/create': {
      id: '/dashboard/events/create'
      path: '/dashboard/events/create'
      fullPath: '/dashboard/events/create'
      preLoaderRoute: typeof DashboardEventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/areas/create': {
      id: '/dashboard/areas/create'
      path: '/dashboard/areas/create'
      fullPath: '/dashboard/areas/create'
      preLoaderRoute: typeof DashboardAreasCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StatusRoute: StatusRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAreasCreateRoute: DashboardAreasCreateRoute,
  DashboardEventsCreateRoute: DashboardEventsCreateRoute,
  DashboardSubareasCreateRoute: DashboardSubareasCreateRoute,
  DashboardRescheduleIndexRoute: DashboardRescheduleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
