import axios from "axios";

const GCAL_BASE_URL = "https://www.googleapis.com/calendar/v3";
const CALENDAR_NAME = "Fluxed";

export const getCalendarId = async (accessToken: string) => {
    const res = await axios.get(`${GCAL_BASE_URL}/users/me/calendarList`, {
        headers: {
            Authorization: `Bearer ${accessToken}`,
        },
    });

    const existingCal = res.data.items?.find(
        (c: any) => c.summary === CALENDAR_NAME,
    );

    if (existingCal) return existingCal.id;

    const newCal = await axios.post(
        `${GCAL_BASE_URL}/calendars`,
        {
            summary: CALENDAR_NAME,
            timeZone: "Asia/Jakarta",
        },
        {
            headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "application/json",
            },
        },
    );
    return newCal.data.id;
};

export const deleteCalendarEvents = async (
    accessToken: string,
    calendarId: string,
) => {
    const safeCalId = encodeURIComponent(calendarId);

    const now = new Date().toISOString();

    const res = await axios.get(
        `${GCAL_BASE_URL}/calendars/${safeCalId}/events?timeMin=${now}&singleEvents=true`,
        {
            headers: { Authorization: `Bearer ${accessToken}` },
        },
    );

    const events = res.data.items || [];

    for (const event of events) {
        try {
            await axios.delete(
                `${GCAL_BASE_URL}/calendars/${safeCalId}/events/${event.id}`,
                {
                    headers: { Authorization: `Bearer ${accessToken}` },
                },
            );
        } catch (err: any) {
            console.warn(`Failed to erase event: ${event.id}:`, err.message);
        }
    }
};
export const insertCalendarEvents = async (
    accessToken: string,
    calendarId: string,
    sessions: any[],
) => {
    for (const session of sessions) {
        try {
            await axios.post(
                `${GCAL_BASE_URL}/calendars/${calendarId}/events`,
                {
                    summary: `Task: ${session.subareaName}`,
                    description: `Area: ${session.area}\n Auto-generated by Fluxed`,
                    start: {
                        dateTime: session.start_time.toISOString(),
                        timeZone: "Asia/Jakarta",
                    },
                    end: {
                        dateTime: session.end_time.toISOString(),
                        timeZone: "Asia/Jakarta",
                    },
                    colorId: "10",
                },
                {
                    headers: {
                        Authorization: `Bearer ${accessToken}`,
                        "Content-Type": "application/json",
                    },
                },
            );
        } catch (error: any) {
            console.error(
                `Failed to insert: ${session.subarea_id}:`,
                error.response?.data || error.message,
            );
        }
    }
};
